require("bufferline").setup({
  options = {
    mode = "buffers",
    themable = true,
    numbers = "buffer_id",
    close_command = "bdelete! %d",
    right_mouse_command = "bdelete! %d",
    left_mouse_command = "buffer %d",
    middle_mouse_command = nil,
    indicator = {
      icon = "│",
      style = "icon",
    },
    buffer_close_icon = "󰅖",
    modified_icon = "● ",
    close_icon = " ",
    left_trunc_marker = " ",
    right_trunc_marker = " ",
    max_name_length = 18,
    max_prefix_length = 15,
    truncate_names = true,
    tab_size = 18,
    diagnostics = true,
    diagnostics_update_in_insert = true,
    diagnostics_update_on_event = true,
    offsets = {
      {
        filetype = "snacks_layout_box",
        text = "󰙅  File Explorer",
        text_align = "center",
        separator = false,
      },
    },
    color_icons = true,
    show_buffer_icons = true,
    show_buffer_close_icons = true,
    show_close_icon = true,
    show_tab_indicators = true,
    show_duplicate_prefix = true,
    duplicates_across_groups = true,
    persist_buffer_sort = true,
    move_wraps_at_ends = true,
    separator_style = { "", "" },
    enforce_regular_tabs = true,
    always_show_bufferline = true,
    auto_toggle_bufferline = true,
    hover = {
      enabled = false,
    },
    pick = {
      alphabet = "abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ1234567890",
    },
  },
})
